
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_TEST_USER'] %>
  password: <%= ENV['PG_TEST_PWD'] %>
  host: localhost
  pool: 5

development:
  <<: *default
  database: status_logger_development

test:
  <<: *default
  database: status_logger_test

production:
  <<: *default
  database: status_logger_production
